FROM crpi-8kvyt6flnal17nk5.cn-beijing.personal.cr.aliyuncs.com/liveno/node:24.20.trixie.slim.vue
LABEL description="node vue 镜像 基于 node:24.20.trixie.slim.vue"

ADD frontend /share/frontend
RUN cd /share/frontend && pnpm install

# crpi-8kvyt6flnal17nk5.cn-beijing.personal.cr.aliyuncs.com/liveno/node:24.20.trixie.slim.frontend

# notes: 该镜像是公开镜像-不得存放任何敏感信息
